### ISSUE TITLE
Deadzone logic is incorrect on AxesToVector3Action

### ISSUE THREAD

**Issue by thestonefox** [ExtendRealityLtd/Tilia.Input.CombinedActions.Unity#21]
### Environment

* Code source: Github master
* Code version: 1.7.0
* Platform version: Unity 2018.3.14f1
* 3rd party dependencies: Oculus Rift S, Oculus Home

### Steps to reproduce

* Empty Unity Scene
* Delete `MainCamera` from scene.
* Add `CameraRigs.UnityXR` camerarig from `"io.extendreality.tilia.camerarigs.unityxr": "1.3.0"`
* Add `Input.UnityInputManager.Oculus.TouchRightController` from `"io.extendreality.tilia.input.unityinputmanager": "1.3.1"`
* Go to `Main Menu -> Edit -> Project Settings -> Input` and change:
  * `Tilia.Input.UnityInputManager_Axis4`:
     * Dead: 0.001
     * Sensitivity: 1
  * `Tilia.Input.UnityInputManager_Axis5`:
     * Dead: 0.001
     * Sensitivity: 1
* Add `Input.CombinedActions.AxesToVector3Action` from `"io.extendreality.tilia.input.combinedactions.unity": "1.7.0"`
* Expand `Input.CombinedActions.AxesToVector3Action -> Internal -> InputType -> Incremental` and disable the `TimeStepExtractor` component (to remove any multiplication by time components for raw axis data).
* Set the `Input.CombinedActions.AxesToVector3Action -> AxesToVector3Action -> LateralAxis` property to `Input.UnityInputManager.Oculus.TouchRightController -> InputActions -> RightThumbstick -> RightThumbstick_HorizontalAxis[4]` GameObject.
* Set the `Input.CombinedActions.AxesToVector3Action -> AxesToVector3Action -> LongitudinalAxis` property to `Input.UnityInputManager.Oculus.TouchRightController -> InputActions -> RightThumbstick -> RightThumbstick_VerticalAxis[5]` GameObject.
* Put Inspector in to Debug Mode
* Run the scene and monitor the `AxesToVector3Action -> <Value>k__Backing Field` Vector3 property.

* Press Up on the controller input and the Z value will change to roughly `1f`
* Start slowly moving the controller input to the right (whilst still pushing fully up). The X value will not change until it becomes above the threshold.

### Current behavior

The deadzones work on per axis basis and not a circular (2d) or spherical (3d) basis:

Current axis functionality:

#### Deadzone on all axes: -0.5 to 0.5

---

![image](https://user-images.githubusercontent.com/1029673/87146773-5c2afb80-c2a3-11ea-982d-df2c2943bb3d.png)
Stick at 0,0 - within both deadzones - output 0,0

---

![image](https://user-images.githubusercontent.com/1029673/87146868-841a5f00-c2a3-11ea-8ab5-210eb53b6e74.png)
Stick at 0.4,0.4 - within both deadzones - output 0,0

---

![image](https://user-images.githubusercontent.com/1029673/87146955-add38600-c2a3-11ea-9080-84e36417ad85.png)
Stick at 0, 1 - LAT out of deadzone, LON in deadzone - output 0,1

---

![image](https://user-images.githubusercontent.com/1029673/87147019-cc398180-c2a3-11ea-84de-f08bbe022dd4.png)
Stick at 0.7, 0.7 - LAT out of deadzone, LON out deadzone - output 0.7,0.7

---

![image](https://user-images.githubusercontent.com/1029673/87147111-fbe88980-c2a3-11ea-9f29-63cc9d1c1d6f.png)
Stick at 0.3, 0.8 - LAT out of deadzone, LON in deadzone - output 0, 0.8

> ^^^ This is the one I think should not give this output.

### Expected behavior

I would expect the threshold to be a circular threshold and not per axis

I would expect it to work like:

![image](https://user-images.githubusercontent.com/1029673/87147265-394d1700-c2a4-11ea-8bc0-7cb4efe182a8.png)
Stick at 0,0 - within both deadzones - output 0,0

---

![image](https://user-images.githubusercontent.com/1029673/87147298-49fd8d00-c2a4-11ea-9f14-78d0f3ea1520.png)
Stick at 0.4,0.4 - within both deadzones - output 0,0

---

![image](https://user-images.githubusercontent.com/1029673/87147309-5255c800-c2a4-11ea-96b5-554b21b106b2.png)
Stick at 0, 1 - LAT out of deadzone, LON in deadzone - output 0,1

---

![image](https://user-images.githubusercontent.com/1029673/87147331-5c77c680-c2a4-11ea-890c-1c4c83f75adf.png)
Stick at 0.7, 0.7 - LAT out of deadzone, LON out deadzone - output 0.7,0.7

---

![image](https://user-images.githubusercontent.com/1029673/87147352-66012e80-c2a4-11ea-9c7b-25da27cb65e9.png)
Stick at 0.3, 0.8 - LAT out of deadzone, LON in deadzone - output 0.3, 0.8

> ^^^ Whilst the LON _is_ in the deadzone, the deadzone only matters when all axes are within it.

**Comment by thestonefox** [comment]
I've got a fix for this, just pending the Zinnia changes to go in before raising.

**Comment by HugoCortell** [comment]
> 
> 
> I've got a fix for this, just pending the Zinnia changes to go in before raising.

That is so great to hear!   
So all we got to do is update when its out and the issue will be fixed? Or will it require extra set up?

**Comment by extendreality** [comment]
Fixed with https://github.com/ExtendRealityLtd/Tilia.Input.CombinedActions.Unity/pull/23

**Comment by extendreality** [comment]
@HugoCortell Yes updating will be enough to fix it.

Although you will probably also need to update your unity input settings have been changed to not rely on the internal Unity Horizontal/Vertical axis data.

You can update these now by going to:

Main Menu -> Window -> Tilia -> Input -> Manage Unity Input Manager Axis Definintions

![image](https://user-images.githubusercontent.com/36199993/87225809-7211ec80-c387-11ea-8c28-620510613047.png)


Then you should see a button letting you delete the existing definitions (used by Tilia only)

![image](https://user-images.githubusercontent.com/36199993/87225815-83f38f80-c387-11ea-9fa6-2d029f7cb7c2.png)


Click the "Delete Input Definitions" button and then wait a moment for the input axis values to delete (go check they're gone in the Project Setting -> Input section), then click the "Add Input Definitions" button

![image](https://user-images.githubusercontent.com/36199993/87225831-a7b6d580-c387-11ea-89c9-f283a02ac6fe.png)

**Comment by HugoCortell** [comment]
https://cdn.discordapp.com/attachments/717121338409484319/731563825756635266/unknown.png

I do not have an option to do so.
